services:
  mysql:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        MYSQL_DATABASE: ${MYSQL_DATABASE}
    container_name: ${MYSQL_CONTAINER_NAME}
    ports:
      - "${MYSQL_PORT}:${MYSQL_PORT}"
    networks:
      - mysql_network
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    env_file:
      - .env

  php:
    image: php:8.0-apache
    container_name: php-container
    ports:
      - "8081:80"
    volumes:
      - ./backend:/var/www/html
    networks:
      - mysql_network
    environment:
      DB_HOST: ${DB_HOST}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      DB_NAME: ${MYSQL_DATABASE}

networks:
  mysql_network:
    driver: bridge

volumes:
  mysql_data:
