version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: ${DB_CONTAINER_NAME}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    networks:
      - mysql_network
    volumes:
      - mysql_data:/var/lib/mysql
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${BACKEND_CONTAINER}
    ports:
      - "8081:80"
    volumes:
      - ./backend:/var/www/html
    networks:
      - mysql_network
    env_file:
      - .env

networks:
  mysql_network:
    driver: bridge

volumes:
  mysql_data:
