services:
  mysql:
    image: mysql:8.0
    container_name: ${DB_CONTAINER_NAME}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    networks:
      - mysql_network
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    env_file:
      - .env

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${BACKEND_CONTAINER}
    ports:
      - "8081:80"
    volumes:
      - ./backend:/var/www/html
      - ./.env:/var/www/html/.env
    networks:
      - mysql_network
    environment:
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}

networks:
  mysql_network:
    driver: bridge

volumes:
  mysql_data:
