version: "3.1"

services:
  mysql:
    image: ${MYSQL_IMAGE}
    container_name: ${MYSQL_CONTAINER_NAME}
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "${MYSQL_PORT}:${MYSQL_PORT}"
    networks:
      - mysql_network
    volumes:
      - mysql_data:/var/lib/mysql

networks:
  mysql_network:
    driver: bridge

volumes:
  mysql_data:
