version: "3.8"

services:
  mysql:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        MYSQL_DATABASE: ${MYSQL_DATABASE}
    container_name: ${MYSQL_CONTAINER_NAME}
    ports:
      - "${MYSQL_PORT}:${MYSQL_PORT}"
    networks:
      - ${MYSQL_NETWORK}
    volumes:
      - ${MYSQL_VOLUME}:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}

networks:
  ${MYSQL_NETWORK}:
    driver: bridge

volumes:
  ${MYSQL_VOLUME}:
